-- ================================
-- Amazon Project - Advanced SQL
-- ================================
-- 22 Advanced Business Problems
-- ================================

/*
1. Top Selling Products
Query the top 10 products by total sales value.
Challenge: Include product name, total quantity sold, and total sales value.
*/

/*
2. Revenue by Category
Calculate total revenue generated by each product category.
Challenge: Include the percentage contribution of each category to total revenue.
*/

/*
3. Average Order Value (AOV)
Compute the average order value for each customer.
Challenge: Include only customers with more than 5 orders.
*/

/*
4. Monthly Sales Trend
Query monthly total sales over the past year.
Challenge: Display the sales trend, grouping by month, return current-month sales, and last-month sales.
*/

/*
5. Customers with No Purchases
Find customers who have registered but never placed an order.
Challenge: List customer details and the time since their registration.
*/

/*
6. List All Products With No Sales
Problem: Identify products that have not been sold at all.
Challenge: Include product name and category details.
*/

/* 
7. Customers with the Highest Spending
Problem: Find the top 5 customers with the highest total spending.
Challenge: Include customer name and total spending amount.
*/ 

/*
8. Most Frequently Purchased Product
Problem: Find the product that has been purchased the most times.
Challenge: Include product name and total quantity purchased.
*/

/*
9. Orders Without Payments
Problem: Find orders that have not yet received any payment.
Challenge: Include order ID, customer name, and order date.
*/

/*
10. Products with the Highest Stock
Problem: Find the top 5 products with the highest remaining stock.
Challenge: Include product name, stock remaining, and last restock date.
*/

/*
Problem 11: Top Customers by State
Identify the top customer in each state based on the total number of orders placed.
Include the customer's name, state, and the total number of orders.
*/

/*
Problem 12: Low Performing Products
Identify products with less than 50 units sold in total.
Include product name, total units sold, and product category.
*/

/*
Problem 13: Orders by Quarter
Calculate the total number of orders placed in each quarter of the last year.
Include the quarter (Q1, Q2, etc.) and the total number of orders.
*/

/*
Problem 14: Sellers Without Sales
Identify sellers who have not made any sales in the current year.
Include seller name, origin, and the last sale date.
*/

/*
-- Problem 15: Top Products by Profit
-- Find the top 5 products with the highest profit.
-- Include product name, total profit, and category.
*/

/*
16. Inventory Stock Alerts
Query products with stock levels below a certain threshold (e.g., less than 10 units).
Challenge: Include the last restock date and warehouse information.
*/

/*
17. Shipping Delays
Identify orders where the shipping date is later than 7 days after the order date.
Challenge: Include customer, order details, and delivery provider.
*/

/*
18. Payment Success Rate
Calculate the percentage of successful payments across all orders.
Challenge: Include breakdowns by payment status (e.g., failed, pending).
*/

/*
20. Store Procedure for Inventory Management
Create a stored procedure to reduce stock in the inventory table based on product quantity sold.
Challenge: After adding any sales records, the procedure should update the stock in the inventory table.
*/

/* End of Business Problem List */
